# Generated by Django 2.1.5 on 2019-01-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth_user',
        ),
    ]
