# Generated by Django 2.1.5 on 2019-01-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator_name', models.CharField(help_text='Enter Stock Name', max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_name', models.CharField(default='NA', help_text='Pick a name for your study', max_length=25, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('indicator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockTrainerApp.Indicator')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='NA', help_text='Pick a name for your portfolio', max_length=25, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_close',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_name',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='stockTrainerApp.Portfolio'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(help_text='Enter Stock Name', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(help_text='Enter Stock Symbol', max_length=5),
        ),
        migrations.AddField(
            model_name='study',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockTrainerApp.Stock'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='study_name',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='stockTrainerApp.Study'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_name',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='stockTrainerApp.Study'),
        ),
    ]
