# Generated by Django 2.1.5 on 2019-01-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='study_id',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='temp',
            field=models.CharField(default='abcd', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='portfolio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockTrainerApp.Portfolio'),
        ),
    ]
