# Generated by Django 2.1.5 on 2019-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0002_auto_20190114_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='APItest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
