# Generated by Django 2.1.5 on 2019-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0002_auto_20190122_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
    ]
