# Generated by Django 2.1.5 on 2019-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0003_auto_20190123_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stock_id',
            field=models.ManyToManyField(to='stockTrainerApp.Stock'),
        ),
    ]
