# Generated by Django 2.1.5 on 2019-01-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0004_user_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stock_id',
            new_name='favorites',
        ),
    ]
