# Generated by Django 2.1.5 on 2019-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0004_remove_apitest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitest',
            name='Value',
        ),
        migrations.AddField(
            model_name='apitest',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
