# Generated by Django 2.1.5 on 2019-01-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0005_auto_20190114_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APItest',
            new_name='Test',
        ),
    ]
