# Generated by Django 2.1.5 on 2019-01-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockTrainerApp', '0006_auto_20190114_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Date',
            field=models.DateField(default='2099-09-09'),
        ),
    ]
